# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trafico_aereo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trafico_aereo.proto',
  package='trafico_aereo',
  syntax='proto3',
  serialized_pb=_b('\n\x13trafico_aereo.proto\x12\rtrafico_aereo\"\x1d\n\x07Request\x12\x12\n\nip_cliente\x18\x01 \x01(\t\"\x1d\n\x08Response\x12\x11\n\tip_server\x18\x01 \x01(\t\"\x17\n\x08\x45mployee\x12\x0b\n\x03pos\x18\x01 \x01(\x05\"\x1c\n\rLeaveFeedback\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x32\x91\x01\n\rServicioAereo\x12;\n\x08\x44\x65spegue\x12\x16.trafico_aereo.Request\x1a\x17.trafico_aereo.Response\x12\x43\n\nAterrizaje\x12\x17.trafico_aereo.Employee\x1a\x1c.trafico_aereo.LeaveFeedbackb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='trafico_aereo.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_cliente', full_name='trafico_aereo.Request.ip_cliente', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=67,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='trafico_aereo.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_server', full_name='trafico_aereo.Response.ip_server', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=98,
)


_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='trafico_aereo.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='trafico_aereo.Employee.pos', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=123,
)


_LEAVEFEEDBACK = _descriptor.Descriptor(
  name='LeaveFeedback',
  full_name='trafico_aereo.LeaveFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='trafico_aereo.LeaveFeedback.pos', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['LeaveFeedback'] = _LEAVEFEEDBACK

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'trafico_aereo_pb2'
  # @@protoc_insertion_point(class_scope:trafico_aereo.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'trafico_aereo_pb2'
  # @@protoc_insertion_point(class_scope:trafico_aereo.Response)
  ))
_sym_db.RegisterMessage(Response)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEE,
  __module__ = 'trafico_aereo_pb2'
  # @@protoc_insertion_point(class_scope:trafico_aereo.Employee)
  ))
_sym_db.RegisterMessage(Employee)

LeaveFeedback = _reflection.GeneratedProtocolMessageType('LeaveFeedback', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEFEEDBACK,
  __module__ = 'trafico_aereo_pb2'
  # @@protoc_insertion_point(class_scope:trafico_aereo.LeaveFeedback)
  ))
_sym_db.RegisterMessage(LeaveFeedback)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class ServicioAereoStub(object):
  """Service. define the methods that the grpc server can expose to the client.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Despegue = channel.unary_unary(
        '/trafico_aereo.ServicioAereo/Despegue',
        request_serializer=Request.SerializeToString,
        response_deserializer=Response.FromString,
        )
    self.Aterrizaje = channel.unary_unary(
        '/trafico_aereo.ServicioAereo/Aterrizaje',
        request_serializer=Employee.SerializeToString,
        response_deserializer=LeaveFeedback.FromString,
        )


class ServicioAereoServicer(object):
  """Service. define the methods that the grpc server can expose to the client.
  """

  def Despegue(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Aterrizaje(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServicioAereoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Despegue': grpc.unary_unary_rpc_method_handler(
          servicer.Despegue,
          request_deserializer=Request.FromString,
          response_serializer=Response.SerializeToString,
      ),
      'Aterrizaje': grpc.unary_unary_rpc_method_handler(
          servicer.Aterrizaje,
          request_deserializer=Employee.FromString,
          response_serializer=LeaveFeedback.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'trafico_aereo.ServicioAereo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaServicioAereoServicer(object):
  """Service. define the methods that the grpc server can expose to the client.
  """
  def Despegue(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def Aterrizaje(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaServicioAereoStub(object):
  """Service. define the methods that the grpc server can expose to the client.
  """
  def Despegue(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Despegue.future = None
  def Aterrizaje(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  Aterrizaje.future = None


def beta_create_ServicioAereo_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('trafico_aereo.ServicioAereo', 'Aterrizaje'): Employee.FromString,
    ('trafico_aereo.ServicioAereo', 'Despegue'): Request.FromString,
  }
  response_serializers = {
    ('trafico_aereo.ServicioAereo', 'Aterrizaje'): LeaveFeedback.SerializeToString,
    ('trafico_aereo.ServicioAereo', 'Despegue'): Response.SerializeToString,
  }
  method_implementations = {
    ('trafico_aereo.ServicioAereo', 'Aterrizaje'): face_utilities.unary_unary_inline(servicer.Aterrizaje),
    ('trafico_aereo.ServicioAereo', 'Despegue'): face_utilities.unary_unary_inline(servicer.Despegue),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_ServicioAereo_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('trafico_aereo.ServicioAereo', 'Aterrizaje'): Employee.SerializeToString,
    ('trafico_aereo.ServicioAereo', 'Despegue'): Request.SerializeToString,
  }
  response_deserializers = {
    ('trafico_aereo.ServicioAereo', 'Aterrizaje'): LeaveFeedback.FromString,
    ('trafico_aereo.ServicioAereo', 'Despegue'): Response.FromString,
  }
  cardinalities = {
    'Aterrizaje': cardinality.Cardinality.UNARY_UNARY,
    'Despegue': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'trafico_aereo.ServicioAereo', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
